# Generated by Django 2.1.5 on 2021-03-15 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('businessName', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10, django.core.validators.MaxLengthValidator(10))])),
                ('email', models.TextField()),
                ('tinNumber', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('eArea', models.TextField()),
                ('Address', models.TextField()),
                ('rgdc', models.TextField()),
                ('classOfBusiness', models.CharField(max_length=25)),
                ('typeOfBusiness', models.CharField(max_length=25)),
                ('expectedFee', models.IntegerField()),
                ('Paid', models.CharField(max_length=10)),
                ('AmountPaid', models.IntegerField()),
                ('agent', models.CharField(max_length=25)),
            ],
        ),
    ]
